# Generated by Django 3.1.5 on 2021-01-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(blank=True, max_length=30)),
                ('house_no', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('job_profession', models.CharField(blank=True, max_length=30)),
                ('job_address', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=30)),
                ('vehicle_details', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=30)),
                ('family_member_details', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(default='00', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='images/')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails')),
            ],
        ),
    ]
