# Generated by Django 3.1.5 on 2021-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_picture',
            field=models.FileField(default='default.jpg', upload_to='images/'),
        ),
    ]
