# Generated by Django 3.1.5 on 2021-01-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0002_auto_20210124_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
