# Generated by Django 3.1.5 on 2021-01-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0004_auto_20210124_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('profile_picture', models.FileField(default='default.jpg', upload_to='images/')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails')),
            ],
        ),
    ]
