# Generated by Django 3.1.5 on 2021-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0006_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='notice',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
