# Generated by Django 3.1.5 on 2021-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0007_chairman_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_sub', models.CharField(max_length=100, null=True)),
                ('about_notice', models.CharField(max_length=999, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('u_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='notice',
        ),
    ]
