# Generated by Django 3.1.5 on 2021-01-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0008_auto_20210129_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
