# Generated by Django 3.1.5 on 2021-01-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0009_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_sub', models.CharField(blank=True, max_length=100)),
                ('about_notice', models.CharField(blank=True, max_length=999)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('u_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
