# Generated by Django 3.1.5 on 2021-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0010_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchmanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('a_id', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=30)),
                ('contact_no', models.CharField(default='00', max_length=30)),
                ('eme_con', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.FileField(default='default.jpg', upload_to='images/')),
            ],
        ),
    ]
