# Generated by Django 3.1.5 on 2021-02-02 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0013_gallary_watchmandetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
