# Generated by Django 3.1.5 on 2021-02-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0014_auto_20210202_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallary',
        ),
    ]
