# Generated by Django 3.1.5 on 2021-02-04 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0016_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='video file')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
