# Generated by Django 3.1.5 on 2021-02-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0017_videogallary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchmanDetails',
        ),
    ]
