# Generated by Django 3.1.5 on 2021-02-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0019_member_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
    ]
