# Generated by Django 3.1.5 on 2021-02-07 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0020_remove_member_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_sub', models.CharField(blank=True, max_length=30)),
                ('event_des', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pic', models.FileField(default='default.jpg', upload_to='images/')),
            ],
        ),
    ]
