# Generated by Django 3.1.5 on 2021-02-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0022_auto_20210208_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sub', models.CharField(blank=True, max_length=100)),
                ('m_des', models.CharField(blank=True, max_length=999)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('u_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
