# Generated by Django 3.1.5 on 2021-02-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_delete_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(default='defaultpic.png', upload_to='images/')),
                ('contact_no', models.CharField(default='000000', max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.user')),
            ],
        ),
    ]
