# Generated by Django 3.1.5 on 2021-02-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_citizen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='citizen',
        ),
    ]
