# Generated by Django 3.1.5 on 2021-02-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0007_citizen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='citizen',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
