# Generated by Django 3.1.5 on 2021-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0009_citizen_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_title', models.CharField(max_length=50)),
                ('law_summary', models.CharField(max_length=50)),
                ('law_rules', models.CharField(max_length=50)),
                ('date_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('law_icon', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
