# Generated by Django 3.1.5 on 2021-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0010_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='law_icon',
            field=models.FileField(default='#', upload_to='images/'),
        ),
    ]
