# Generated by Django 3.1.5 on 2021-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0011_auto_20210203_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='law_rules',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='law',
            name='law_summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='law',
            name='law_title',
            field=models.CharField(max_length=500),
        ),
    ]
