# Generated by Django 3.1.5 on 2021-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0012_auto_20210203_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='law_icon',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
