# Generated by Django 3.1.5 on 2021-02-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0013_auto_20210203_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='law',
        ),
    ]
