# Generated by Django 3.1.5 on 2021-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0014_delete_law'),
    ]

    operations = [
        migrations.CreateModel(
            name='law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_title', models.CharField(max_length=500)),
                ('law_summary', models.CharField(max_length=500)),
                ('law_rules1', models.CharField(max_length=200)),
                ('law_rules2', models.CharField(max_length=200)),
                ('law_rules3', models.CharField(max_length=200)),
                ('law_rules4', models.CharField(max_length=200)),
                ('law_rules5', models.CharField(max_length=200)),
                ('date_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('law_icon', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
