# Generated by Django 3.1.5 on 2021-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0016_remove_law_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='profile_pic',
            field=models.FileField(default='default-pic.png', upload_to='images/'),
        ),
    ]
