# Generated by Django 3.1.5 on 2021-02-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0017_auto_20210204_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='citizen',
        ),
    ]
