# Generated by Django 3.1.5 on 2021-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0019_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='crime_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_category_name', models.CharField(max_length=500)),
            ],
        ),
    ]
