# Generated by Django 3.1.5 on 2021-02-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0022_delete_sub_crime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_crime_category_name', models.CharField(max_length=500)),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.crime_category')),
            ],
        ),
    ]
