# Generated by Django 3.1.5 on 2021-02-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0023_sub_crime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_crime',
        ),
    ]
