# Generated by Django 3.1.5 on 2021-02-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0027_auto_20210205_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(default='default-pic.png', upload_to='images/')),
                ('contact_no', models.CharField(default='000000', max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_description', models.CharField(max_length=500)),
                ('complaint_no', models.CharField(max_length=100)),
                ('proof_img', models.FileField(upload_to='images/')),
                ('proof_video', models.FileField(null=True, upload_to='videos/', verbose_name='video file')),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen')),
            ],
        ),
    ]
