# Generated by Django 3.1.5 on 2021-02-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=30)),
                ('family_contact_no', models.CharField(blank=True, max_length=30)),
                ('age', models.CharField(blank=True, max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=30)),
                ('photo_id', models.FileField(upload_to='images/')),
                ('profile_picture', models.FileField(default='defaultpic.png', upload_to='images/')),
                ('status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
    ]
